version: "3.8"
# Docker Compose configuration for Spark Master, Worker, and History Server
services:
  spark-master:
    container_name: da-spark-master
    build:
      #Defino como contexto la raiz del proyecto para poder incluir dentro del Dockerfile los archivos de la carpeta app, que es donde est√°n los scripts de Spark.
      context: ../..
      dockerfile: infra/spark/Dockerfile
      
    image: da-spark-image
      #Paso el entrypoint.sh con el comando levantar el master.
    entrypoint: ["./entrypoint.sh", "master"]
    networks:
      - infra_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-history-server:
    container_name: da-spark-history
    image: da-spark-image
      #Paso el entrypoint.sh con el comando levantar el history server.
    entrypoint: ["./entrypoint.sh", "history"]
    depends_on:
      - spark-master
    networks:
      - infra_net
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - "18080:18080"

  spark-worker:
    image: da-spark-image
      #Paso el entrypoint.sh con el comando levantar el worker.
    entrypoint: ["./entrypoint.sh", "worker"]
    depends_on:
      - spark-master
    networks:
      - infra_net
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs:

networks:
  infra_net:
    external: true
